services:
  frontend:
    container_name: frontend
    ports:
      - "3000:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
  backend:
    container_name: backend
    ports:
      - "5000:5000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/app"
      - "~/.aws/:/root/.aws:ro"
      
