services:
  frontend:
    container_name: frontend
    image: node:18-alpine
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
  backend:
    container_name: backend
    image: node:19-alpine3.16
    ports:
      - "5000:5000"
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - "~/.aws/:/root/.aws:ro"
  # mongodb_container:
  #   container_name: database
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongodb_db_container:/data/db

volumes:
  frontend:
  backend:
  # mongodb_db_container:
      
