FROM node:19-alpine3.16

WORKDIR /app

# Copy package.json first to utilize caching layers
# Wildc ard for both package.json and package-lock.json
COPY package*.json ./

RUN npm install --include=dev

COPY . .

CMD npm run dev

EXPOSE 5000